const STG=["Novo","Contato Feito","Proposta Enviada","Em Negociação","Ganho","Cliente Recorrente","Perdido"],
COR=["#0e9fc4","#3b6fd8","#c9a20a","#d9531e","#1f9d55","#0b7a62","#8b97a3"],REC=["Ganho","Cliente Recorrente"],
SCT=["Lead","Prospect","Cliente","Inativo"],TIP=["Ligação","Reunião","E-mail","Follow-up","Outro"],
FPG=["Dinheiro","Pix","Cartão de Crédito","Cartão de Débito","Boleto","Transferência","Outro"],
STT=["Pendente","Concluída","Cancelada"],ALL="Todas as categorias",SEM="(Sem categoria)",VER="2.0.0-html";
let D={contatos:[],negocios:[],tarefas:[],interacoes:[],produtos:[],negocio_produtos:[],empresa:{}},S={},tm;
const $=s=>document.querySelector(s),
h=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),
RF=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),$$=v=>v==null||v===''?'-':RF.format(v),
num=s=>{s=String(s??'').trim();if(!s)return null;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return isNaN(n)?NaN:n},
fq=q=>String(q).replace('.',','),now=()=>new Date(Date.now()-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,19).replace('T',' '),
fdt=s=>/^\d{4}-\d\d-\d\d/.test(s||'')?s.slice(8,10)+'/'+s.slice(5,7)+'/'+s.slice(0,4):s||'',
g=(t,id)=>D[t].find(x=>x.id==id),nid=t=>Math.max(0,...D[t].map(x=>x.id))+1,fd=f=>Object.fromEntries(new FormData(f)),
pt=(a,b)=>(a||'').localeCompare(b||'','pt'),st=m=>$('#st').textContent=m,
cats=()=>[...new Map(D.produtos.map(p=>(p.categoria||'').trim()).filter(Boolean).map(c=>[c.toLowerCase(),c])).values()].sort(pt),
catOpts=()=>[ALL,...cats(),...(D.produtos.some(p=>!(p.categoria||'').trim())?[SEM]:[])],
clist=()=>[['','(sem contato)'],...D.contatos.slice().sort((a,b)=>pt(a.nome,b.nome)).map(c=>[c.id,`${c.nome} (#${c.id})`])],
dt=n=>!n.desconto?'-':n.tipo_desconto=='percentual'?n.desconto.toFixed(2).replace('.',',')+'%':$$(n.desconto),
pill=s=>`<span class="pl" style="--c:${COR[STG.indexOf(s)]||'#888'}">${h(s)}</span>`,
prods=(q='',cat=ALL)=>{q=q.toLowerCase();return D.produtos.filter(p=>{const k=(p.categoria||'').trim();return(cat==ALL||(cat==SEM?!k:k.toLowerCase()==cat.toLowerCase()))&&(!q||`${p.nome} ${p.descricao||''} ${k}`.toLowerCase().includes(q))}).sort((a,b)=>{const x=(a.categoria||'').trim(),y=(b.categoria||'').trim();return(!x-!y)||pt(x,y)||pt(a.nome,b.nome)})},
op=(x,v)=>{const[a,b]=Array.isArray(x)?x:[x,x];return`<option value="${h(a)}"${a==(v??'')?' selected':''}>${h(b)}</option>`},
F=(l,n,v,t='text',o='',w)=>`<label class="${w?'w':''}">${l}${t=='select'?`<select name="${n}">${o.map(x=>op(x,v)).join('')}</select>`:t=='area'?`<textarea name="${n}" rows="3">${h(v)}</textarea>`:`<input name="${n}" type="${t}" value="${h(v)}" ${o}>`}</label>`,
T=(hd,rows,emp,right=[],cls=()=>'')=>`<div class="tw"><table><thead><tr>${hd.map((x,i)=>`<th class="${right.includes(i)?'r':''}">${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map((r,j)=>`<tr class="${cls(j)}">${r.map((c,i)=>`<td class="${right.includes(i)?'r':''}">${c??''}</td>`).join('')}</tr>`).join(''):`<tr><td class="em" colspan="${hd.length}">${emp}</td></tr>`}</tbody></table></div>`,
AC=(a,id)=>`<span class="ac">${a.map(([k,l])=>`<button data-a="${k}" data-id="${id}" class="${k=='x'?'x':''}">${l}</button>`).join('')}</span>`;

/* ---------- persistência (IndexedDB) ---------- */
const idb=()=>new Promise((ok,no)=>{const r=indexedDB.open('crm_offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('k');r.onsuccess=()=>ok(r.result);r.onerror=no});
const load=async()=>{try{const d=await idb();return await new Promise(ok=>{const q=d.transaction('k').objectStore('k').get('db');q.onsuccess=()=>ok(q.result);q.onerror=()=>ok()})}catch{}};
const save=()=>{clearTimeout(tm);tm=setTimeout(async()=>{try{(await idb()).transaction('k','readwrite').objectStore('k').put(D,'db')}catch{alert('Não foi possível gravar os dados neste navegador. Faça um backup agora.')}},50)};
const dl=(n,t,m)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:m}));a.download=n;a.click()};
const stamp=()=>now().replace(/\D/g,'').replace(/^(\d{8})/,'$1_');

/* ---------- janelas e impressão ---------- */
function dlg(title,body,ok){const d=$('#dlg');d.oninput=null;d.innerHTML=`<form><h2>${title}</h2><div class="fb">${body}</div><div class="fa"><button type="button" class="b" id="cx">Cancelar</button><button class="b p">Salvar</button></div></form>`;d.showModal();$('#cx').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();if(ok(e.target)!==false)d.close()}}
const commit=m=>{save();render();m&&st(m)};
const cab=()=>{const e=D.empresa||{};return`<div class="cab">${e.logo?`<img src="${e.logo}">`:''}<div><h1>${h(e.nome||'(Nome da empresa não configurado)')}</h1><p>${h(e.endereco)}</p>${e.cnpj?`<p>CNPJ: ${h(e.cnpj)}</p>`:''}${e.contato?`<p>Contato: ${h(e.contato)}</p>`:''}</div></div>`};
const PCSS=`body{font:13px Arial,sans-serif;color:#222;margin:30px}.cab{display:flex;align-items:center;gap:20px;border-bottom:3px solid #333;padding-bottom:14px;margin-bottom:18px}.cab img{max-height:90px;max-width:180px;object-fit:contain}h1{margin:0 0 6px;font-size:22px}p{margin:2px 0}h2{font-size:16px;margin:20px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:6px 9px;text-align:left}th{background:#f0f0f0}.r{text-align:right;white-space:nowrap}tr.g td{background:#e4e4e4;font-weight:bold}.ft{margin-top:22px;font-size:11px;color:#888;text-align:right}.np{position:fixed;top:10px;right:10px;padding:8px 14px}@media print{.np{display:none}body{margin:10mm}}`;
function doc(title,body){const w=window.open('','_blank');if(!w)return alert('Permita pop-ups para este arquivo e tente de novo.');w.document.write(`<!DOCTYPE html><html lang="pt-BR"><meta charset="utf-8"><title>${h(title)}</title><style>${PCSS}</style><button class="np" onclick="print()">Imprimir / Salvar PDF</button>${cab()}${body}<div class="ft">Gerado por CRM Vorax em ${new Date().toLocaleString('pt-BR')}</div>`);w.document.close()}
const semEmpresa=()=>{if(!(D.empresa?.nome||'').trim())alert("Dica: configure os dados da empresa (nome, endereço, CNPJ, contato e logomarca) na aba Empresa para deixar a impressão mais profissional.")};

/* ---------- abas ---------- */
const V={
dashboard:{title:'Dashboard',bar:()=>'',list(){
 const N=D.negocios,s=a=>a.reduce((t,x)=>t+(x.valor||0),0);
 if(!D.contatos.length&&!N.length&&!D.produtos.length)return`<div class="cd"><b>Nenhum dado ainda</b><p>Importe seus dados na aba Backup (por exemplo, o arquivo crm_dados.json) ou comece cadastrando contatos e produtos.</p><button class="b p" data-go="backup">Ir para Backup</button></div>`;
 const K=[['Contatos',D.contatos.length],['Negócios',N.length],['Pipeline em aberto',$$(s(N.filter(x=>!REC.includes(x.estagio)&&x.estagio!='Perdido')))],['Total ganho',$$(s(N.filter(x=>REC.includes(x.estagio))))],['Clientes recorrentes',new Set(N.filter(x=>x.estagio=='Cliente Recorrente'&&x.contato_id).map(x=>x.contato_id)).size],['Tarefas pendentes',D.tarefas.filter(x=>x.status=='Pendente').length]];
 return`<div class="cards">${K.map(([a,b])=>`<div class="cd"><b>${b}</b><span>${a}</span></div>`).join('')}</div><h2>Negócios por estágio</h2><div class="cd">${STG.map((e,i)=>{const q=N.filter(x=>x.estagio==e).length;return`<div class="sg"><span>${e}</span><i><u style="width:${q/Math.max(N.length,1)*100}%;background:${COR[i]}"></u></i><em>${q}</em></div>`}).join('')}</div>`}},

contatos:{title:'Contatos',
bar:()=>`<input data-s="q" type="search" placeholder="Buscar nome, empresa, telefone ou e-mail"><button class="b p" data-a="n">Novo contato</button><button class="b" data-a="imp">Importar CSV</button><button class="b" data-a="exp">Exportar CSV</button>`,
list(){const q=S.q.toLowerCase(),L=D.contatos.filter(c=>!q||[c.nome,c.empresa,c.telefone,c.email].some(v=>(v||'').toLowerCase().includes(q))).sort((a,b)=>pt(a.nome,b.nome));st(`${L.length} contato(s) exibido(s)`);
 return T(['ID','Nome','Empresa','Telefone','E-mail','Status',''],L.map(c=>[c.id,h(c.nome),h(c.empresa),h(c.telefone),h(c.email),h(c.status),AC([['e','Editar'],['i','Interação'],['x','Excluir']],c.id)]),'Nenhum contato encontrado.')},
form(c){const v=c||{status:'Lead'};dlg(c?'Editar contato':'Novo contato',F('Nome *','nome',v.nome,'text','required',1)+F('Empresa','empresa',v.empresa)+F('Telefone','telefone',v.telefone)+F('E-mail','email',v.email,'email')+F('Origem (ex: Indicação, Site)','origem',v.origem)+F('Status','status',v.status,'select',SCT)+F('Endereço','endereco',v.endereco,'text','',1)+F('Tags (separadas por vírgula)','tags',v.tags,'text','',1)+F('Observações','observacoes',v.observacoes,'area','',1),f=>{const d=fd(f);d.nome=d.nome.trim();if(c)Object.assign(c,d,{atualizado_em:now()});else D.contatos.push({id:nid('contatos'),...d,criado_em:now(),atualizado_em:now()});commit('Contato salvo.')})},
n(){this.form()},e(id){this.form(g('contatos',id))},
x(id){if(!confirm('Excluir este contato? Negócios e tarefas vinculados NÃO serão excluídos, apenas desvinculados.'))return;D.contatos=D.contatos.filter(c=>c.id!=id);D.interacoes=D.interacoes.filter(x=>x.contato_id!=id);[...D.negocios,...D.tarefas].forEach(x=>x.contato_id==id&&(x.contato_id=null));commit('Contato excluído.')},
i(id){const hist=D.interacoes.filter(x=>x.contato_id==id).sort((a,b)=>b.data.localeCompare(a.data));dlg('Interação — '+h(cnome(id)),`<div class="w">${hist.length?hist.map(x=>`<p><small>${h(x.data)}</small><br>${h(x.texto)}</p>`).join(''):'<p class="em">Nenhuma interação registrada.</p>'}</div><label class="w">Descreva o contato realizado (ligação, e-mail, reunião...)<textarea name="texto" rows="3" required></textarea></label>`,f=>{D.interacoes.push({id:nid('interacoes'),contato_id:id,texto:fd(f).texto.trim(),data:now()});commit('Interação registrada no histórico do contato.')})},
imp(){const i=document.createElement('input');i.type='file';i.accept='.csv,.txt';i.onchange=async()=>{const rows=csv((await i.files[0].text()).replace(/^\uFEFF/,''));let ok=0,bad=[];rows.forEach((r,n)=>{if(!r[0]?.trim())return;let t=(r[1]||'').trim();t=(t.startsWith('+')?'+':'')+t.replace(/\D/g,'');const dg=t.replace('+','');if(t&&!(dg.length>=8&&dg.length<=15)){bad.push(`Linha ${n+1}: '${r[1]}'`);return}D.contatos.push({id:nid('contatos'),nome:r[0].trim(),telefone:t,email:(r[2]||'').trim(),empresa:(r[3]||'').trim(),status:'Lead',criado_em:now(),atualizado_em:now()});ok++});commit();alert(`${ok} contato(s) importado(s) com sucesso.`+(bad.length?`\n\n${bad.length} número(s) inválido(s) ignorados:\n`+bad.slice(0,20).join('\n'):''))};i.click()},
exp(){const R=[['nome','telefone','email','empresa','status','origem','observacoes'],...D.contatos.slice().sort((a,b)=>pt(a.nome,b.nome)).map(c=>[c.nome,c.telefone,c.email,c.empresa,c.status,c.origem,c.observacoes])];dl('contatos.csv','\uFEFF'+R.map(r=>r.map(c=>`"${String(c??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'),'text/csv');st('Contatos exportados para CSV.')}},

negocios:{title:'Negócios',
bar:()=>`<select data-s="est">${['Todos',...STG].map(x=>op(x)).join('')}</select><button class="b p" data-a="n">Novo negócio</button>`,
list(){const L=D.negocios.filter(n=>S.est=='Todos'||n.estagio==S.est).sort((a,b)=>(b.criado_em||'').localeCompare(a.criado_em||''));st(`${L.length} negócio(s) - Total: ${$$(L.reduce((t,n)=>t+(n.valor||0),0))}`);
 return T(['ID','Título','Contato','Produto(s)','Valor final','Desconto','Pagamento','Vendedor','Estágio','Previsão',''],L.map(n=>[n.id,h(n.titulo),h(cnome(n.contato_id)||'-'),h(pnomes(n)||'-'),$$(n.valor),dt(n),h(n.forma_pagamento||'-'),h(n.vendedor||'-'),pill(n.estagio),fdt(n.previsao_fechamento),AC([['e','Editar'],['p','Imprimir'],['x','Excluir']],n.id)]),'Nenhum negócio encontrado.',[4,5])},
n(){this.form()},e(id){this.form(g('negocios',id))},
x(id){if(!confirm('Excluir este negócio?'))return;D.negocios=D.negocios.filter(n=>n.id!=id);D.negocio_produtos=D.negocio_produtos.filter(x=>x.negocio_id!=id);D.tarefas.forEach(t=>t.negocio_id==id&&(t.negocio_id=null));commit('Negócio excluído.')},
form(n){const v=n||{estagio:STG[0],forma_pagamento:FPG[0],tipo_desconto:'valor'};let it=n?D.negocio_produtos.filter(x=>x.negocio_id==n.id).map(x=>({...x})):[];
 dlg(n?'Editar negócio':'Novo negócio',F('Título do negócio *','titulo',v.titulo,'text','required',1)+F('Contato vinculado','contato_id',v.contato_id,'select',clist(),'',1)+
 `<div class="w pb"><b>Produtos</b><div class="bar"><input id="pq" type="search" placeholder="Buscar produto"><select id="pc">${catOpts().map(c=>op(c)).join('')}</select></div><div class="bar"><select id="ps"></select><input id="pn" type="number" min="0.01" step="any" value="1" style="width:80px" aria-label="Quantidade"><button type="button" class="b" id="pa">+ Adicionar</button></div><table><tbody id="it"></tbody></table></div>`+
 F('Valor dos produtos (R$)','valor_bruto',v.valor_bruto?fq(v.valor_bruto):'')+F('Forma de pagamento','forma_pagamento',v.forma_pagamento,'select',FPG)+F('Tipo de desconto','tipo_desconto',v.tipo_desconto,'select',[['valor','Valor (R$)'],['percentual','Percentual (%)']])+F('Desconto (0 se não houver)','desconto',v.desconto?fq(v.desconto):'')+F('Vendedor responsável','vendedor',v.vendedor)+F('Estágio','estagio',v.estagio,'select',STG)+F('Previsão de fechamento','previsao_fechamento',v.previsao_fechamento,'date')+F('Observações','observacoes',v.observacoes,'area','',1)+'<div class="w tot" id="vf"></div>',
 f=>{const d=fd(f),b=num(d.valor_bruto),ds=num(d.desconto);if(isNaN(b)||isNaN(ds))return alert('Valor ou desconto inválido.'),false;const B=b||0,X=ds||0,id=n?n.id:nid('negocios'),
  o={titulo:d.titulo.trim(),contato_id:d.contato_id?+d.contato_id:null,valor_bruto:B,desconto:X,tipo_desconto:d.tipo_desconto,valor:Math.max(B-(d.tipo_desconto=='percentual'?B*X/100:X),0),forma_pagamento:d.forma_pagamento,vendedor:d.vendedor.trim(),estagio:d.estagio,previsao_fechamento:d.previsao_fechamento,observacoes:d.observacoes.trim(),atualizado_em:now()};
  if(n)Object.assign(n,o);else D.negocios.push({id,...o,criado_em:now()});
  D.negocio_produtos=D.negocio_produtos.filter(x=>x.negocio_id!=id);let k=nid('negocio_produtos');it.forEach(x=>D.negocio_produtos.push({id:k++,negocio_id:id,produto_id:x.produto_id,nome_produto:x.nome_produto,quantidade:x.quantidade,preco_unitario:x.preco_unitario}));commit('Negócio salvo.')});
 const d=$('#dlg'),q=s=>d.querySelector(s),
 calc=()=>{const b=num(q('[name=valor_bruto]').value)||0,x=num(q('[name=desconto]').value)||0;q('#vf').textContent='Valor final: '+$$(Math.max(b-(q('[name=tipo_desconto]').value=='percentual'?b*x/100:x),0))},
 rec=()=>{q('[name=valor_bruto]').value=it.reduce((s,x)=>s+x.quantidade*x.preco_unitario,0).toFixed(2).replace('.',',');calc()},
 draw=()=>q('#it').innerHTML=it.length?it.map((x,i)=>`<tr><td>${h(x.nome_produto)}</td><td>${fq(x.quantidade)}</td><td class="r">${$$(x.preco_unitario)}</td><td class="r">${$$(x.quantidade*x.preco_unitario)}</td><td><button type="button" class="b" data-r="${i}" aria-label="Remover">×</button></td></tr>`).join(''):'<tr><td class="em">Nenhum produto adicionado.</td></tr>',
 fil=()=>{const L=prods(q('#pq').value,q('#pc').value);q('#ps').innerHTML=L.map(p=>`<option value="${p.id}">${h(p.nome)} (${$$(p.preco_venda)})</option>`).join('')||'<option value="">Nenhum produto</option>'};
 q('#pq').oninput=q('#pc').onchange=fil;
 q('#pa').onclick=()=>{const p=g('produtos',q('#ps').value),k=num(q('#pn').value);if(!p)return alert('Escolha um produto cadastrado para adicionar.');if(!k||k<=0)return alert('Quantidade inválida. Informe um número maior que zero.');it.push({produto_id:p.id,nome_produto:p.nome,quantidade:k,preco_unitario:p.preco_venda||0});q('#pn').value=1;draw();rec()};
 q('#it').onclick=e=>{const i=e.target.dataset.r;if(i!=null){it.splice(i,1);draw();rec()}};
 d.oninput=calc;fil();draw();v.valor_bruto?calc():rec()},
p(id){semEmpresa();const n=g('negocios',id),c=g('contatos',n.contato_id)||{},it=D.negocio_produtos.filter(x=>x.negocio_id==id),kv=(a,b)=>b&&b!='-'?`<tr><th style="width:220px">${a}</th><td>${b}</td></tr>`:'';
 doc('Negócio #'+id,`<p><b style="font-size:19px">Negócio #${n.id}: ${h(n.titulo)}</b></p><p style="color:#777">Criado em ${h(n.criado_em)}</p><h2>Dados do contato / cliente</h2><table>${kv('Nome',h(c.nome))+kv('Empresa',h(c.empresa))+kv('Telefone',h(c.telefone))+kv('E-mail',h(c.email))+kv('Endereço',h(c.endereco))||'<tr><td>Nenhum contato vinculado.</td></tr>'}</table><h2>Produtos</h2><table><tr><th>Produto</th><th>Qtd.</th><th class="r">Preço unit.</th><th class="r">Subtotal</th></tr>${it.map(x=>`<tr><td>${h(x.nome_produto||'Produto removido')}</td><td>${fq(x.quantidade)}</td><td class="r">${$$(x.preco_unitario)}</td><td class="r">${$$((x.quantidade||0)*(x.preco_unitario||0))}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum produto vinculado a este negócio.</td></tr>'}</table><h2>Dados do negócio</h2><table>${kv('Valor do(s) produto(s)',$$(n.valor_bruto))+kv('Desconto',dt(n))+kv('Valor final',`<b>${$$(n.valor)}</b>`)+kv('Forma de pagamento',h(n.forma_pagamento))+kv('Vendedor responsável',h(n.vendedor))+kv('Estágio',h(n.estagio))+kv('Previsão de fechamento',fdt(n.previsao_fechamento))}</table>${n.observacoes?`<h2>Observações</h2><p style="white-space:pre-wrap">${h(n.observacoes)}</p>`:''}`)}},

produtos:{title:'Produtos',
bar:()=>`<input data-s="q" type="search" placeholder="Buscar produto"><select data-s="cat" aria-label="Categoria">${catOpts().map(c=>op(c)).join('')}</select><button class="b p" data-a="n">Novo produto</button><button class="b" data-a="imp">Imprimir lista</button>`,
list(){const L=prods(S.q,S.cat);st(`${L.length} produto(s) exibido(s)`);return T(['ID','Produto','Categoria','Descrição','Preço de custo','Preço de venda',''],L.map(p=>[p.id,h(p.nome),h(p.categoria),h(p.descricao),$$(p.preco_custo),$$(p.preco_venda),AC([['e','Editar'],['x','Excluir']],p.id)]),'Nenhum produto encontrado.',[4,5])},
n(){this.form()},e(id){this.form(g('produtos',id))},
form(p){const v=p||{};dlg(p?'Editar produto':'Novo produto',F('Nome do produto *','nome',v.nome,'text','required',1)+F('Descrição','descricao',v.descricao,'area','',1)+F('Categoria (escolha ou digite uma nova)','categoria',v.categoria,'text','list="cl"',1)+`<datalist id="cl">${cats().map(c=>`<option value="${h(c)}">`).join('')}</datalist>`+F('Preço de venda (R$) *','preco_venda',v.preco_venda!=null?fq(v.preco_venda):'','text','required inputmode="decimal"')+F('Preço de custo (R$) — opcional','preco_custo',v.preco_custo!=null?fq(v.preco_custo):'','text','inputmode="decimal"'),f=>{const d=fd(f),pv=num(d.preco_venda),pc=num(d.preco_custo);if(pv==null||isNaN(pv))return alert('Preço de venda inválido. Use apenas números (ex: 49,90).'),false;if(isNaN(pc))return alert('Preço de custo inválido. Deixe em branco ou use apenas números.'),false;
 const o={nome:d.nome.trim(),descricao:d.descricao.trim(),categoria:d.categoria.trim()||null,preco_venda:pv,preco_custo:pc,atualizado_em:now()};if(p)Object.assign(p,o);else D.produtos.push({id:nid('produtos'),...o,criado_em:now()});S.cat=ALL;commit('Produto salvo.')})},
x(id){if(!confirm('Excluir este produto? Negócios que já o usam continuam mostrando o nome dele.'))return;D.produtos=D.produtos.filter(p=>p.id!=id);D.negocio_produtos.forEach(x=>x.produto_id==id&&(x.produto_id=null));commit('Produto excluído.')},
imp(){const L=prods('',S.cat);if(!L.length)return alert('Não há produtos cadastrados para imprimir.');const cs=confirm('Incluir o preço de custo na impressão?\n\n(Em listas de preços para clientes costuma-se mostrar só o preço de venda.)');semEmpresa();
 const any=L.some(p=>(p.categoria||'').trim());let g0=null;const rows=L.map(p=>{const k=(p.categoria||'').trim();let r='';if(any&&k.toLowerCase()!==g0){g0=k.toLowerCase();r=`<tr class="g"><td colspan="${cs?4:3}">${h(k||SEM)}</td></tr>`}return r+`<tr><td>${h(p.nome)}</td><td>${h(p.descricao).replace(/\n/g,'<br>')}</td>${cs?`<td class="r">${$$(p.preco_custo)}</td>`:''}<td class="r">${$$(p.preco_venda)}</td></tr>`}).join('');
 doc('Lista de Produtos',`<h2>Lista de produtos${S.cat!=ALL?' - '+h(S.cat):''}</h2><table><tr><th>Produto</th><th>Descrição</th>${cs?'<th class="r">Preço de custo</th>':''}<th class="r">Preço de venda</th></tr>${rows}</table>`)}},

top:{title:'Top Clientes',
bar:()=>`<label><input type="checkbox" data-s="rec" checked> Considerar apenas negócios Ganhos / Clientes Recorrentes</label>`,
list(){const m={};D.negocios.forEach(n=>{const c=g('contatos',n.contato_id);if(!c||(S.rec&&!REC.includes(n.estagio)))return;const r=m[c.id]??={c,q:0,v:0,r:0};r.q++;r.v+=n.valor||0;if(n.estagio=='Cliente Recorrente')r.r=1});
 const L=Object.values(m).filter(r=>r.v>0).sort((a,b)=>b.v-a.v);st(`${L.length} cliente(s) no ranking — Total: ${$$(L.reduce((t,r)=>t+r.v,0))}`);
 return T(['#','Cliente','Empresa','Status','Nº negócios','Recorrente?','Valor total gerado'],L.map((r,i)=>[i+1,h(r.c.nome),h(r.c.empresa),h(r.c.status),r.q,r.r?'Sim':'-',$$(r.v)]),'Nenhum cliente com negócios no critério escolhido.',[6],i=>['o','pr','bz'][i]||'')}},

tarefas:{title:'Tarefas',
bar:()=>`<select data-s="stt" aria-label="Status">${['Todas',...STT].map(x=>op(x)).join('')}</select><button class="b p" data-a="n">Nova tarefa</button>`,
list(){const hoje=now().slice(0,10),L=D.tarefas.filter(t=>S.stt=='Todas'||t.status==S.stt).sort((a,b)=>(a.data_prevista||'').localeCompare(b.data_prevista||''));st(`${L.length} tarefa(s)`);
 return T(['Título','Tipo','Contato','Data prevista','Status',''],L.map(t=>[h(t.titulo),h(t.tipo),h(cnome(t.contato_id)),t.status=='Pendente'&&t.data_prevista&&t.data_prevista<hoje?`<span style="color:var(--rd)">${fdt(t.data_prevista)} (atrasada)</span>`:fdt(t.data_prevista),h(t.status),AC([...(t.status=='Pendente'?[['c','Concluir']]:[]),['e','Editar'],['x','Excluir']],t.id)]),'Nenhuma tarefa encontrada.')},
n(){this.form()},e(id){this.form(g('tarefas',id))},
form(t){const v=t||{tipo:'Follow-up',status:'Pendente'};dlg(t?'Editar tarefa':'Nova tarefa',F('Título da tarefa *','titulo',v.titulo,'text','required',1)+F('Tipo','tipo',v.tipo,'select',TIP)+F('Contato vinculado','contato_id',v.contato_id,'select',clist())+F('Data prevista','data_prevista',v.data_prevista,'date')+F('Status','status',v.status,'select',STT)+F('Observações','observacoes',v.observacoes,'area','',1),f=>{const d=fd(f),o={...d,titulo:d.titulo.trim(),contato_id:d.contato_id?+d.contato_id:null};if(t)Object.assign(t,o);else D.tarefas.push({id:nid('tarefas'),negocio_id:null,...o,criado_em:now()});commit('Tarefa salva.')})},
c(id){g('tarefas',id).status='Concluída';commit('Tarefa concluída.')},
x(id){if(confirm('Excluir esta tarefa?')){D.tarefas=D.tarefas.filter(t=>t.id!=id);commit('Tarefa excluída.')}}},

empresa:{title:'Empresa',bar:()=>'',
list(){const e=D.empresa||{};S.logo=undefined;return`<p style="margin:0;color:var(--mu)">Estes dados aparecem no cabeçalho das impressões.</p><div class="form">${F('Nome da empresa *','nome',e.nome,'text','id="en"',1)+F('Endereço','endereco',e.endereco,'text','id="ee"',1)+F('CNPJ','cnpj',e.cnpj,'text','id="ec"')+F('Contato (telefone/e-mail)','contato',e.contato,'text','id="et"')}<label class="w">Logomarca<input type="file" id="lg" accept="image/*"></label><div class="w"><img id="pv" alt="Logomarca" ${e.logo?`src="${e.logo}"`:'hidden'}></div><div class="w bar"><button class="b p" data-a="sv">Salvar dados da empresa</button><button class="b" data-a="rl">Remover logomarca</button></div></div>`},
sv(){const n=$('#en').value.trim();if(!n)return alert('Informe o nome da empresa.');D.empresa={...D.empresa,nome:n,endereco:$('#ee').value.trim(),cnpj:$('#ec').value.trim(),contato:$('#et').value.trim()};if(S.logo!==undefined)D.empresa.logo=S.logo;commit('Dados da empresa atualizados.')},
rl(){D.empresa.logo=null;commit('Logomarca removida.')}},

backup:{title:'Backup',bar:()=>'',
list(){return`<div class="form"><p class="w" style="margin:0">Os dados ficam salvos <b>neste navegador</b>, neste computador. Limpar os dados do navegador apaga o CRM — faça backup com frequência, principalmente antes de formatar, trocar de computador ou atualizar o arquivo.</p><div class="w bar"><button class="b p" data-a="exp">Exportar backup (.json)</button><button class="b" data-a="imp">Importar backup (.json)</button></div><p class="w" style="margin:0;color:var(--mu)">Ao importar, uma cópia de segurança dos dados atuais é baixada automaticamente antes de substituí-los.</p></div>`},
exp(pre){dl(`${pre=='pre'?'pre_import_backup':'backup_crm'}_${stamp()}.json`,JSON.stringify({app:'CRM Vorax',versao:VER,gerado_em:new Date().toISOString(),...D}),'application/json');pre!='pre'&&st('Backup exportado.')},
imp(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{let j;try{j=JSON.parse(await i.files[0].text())}catch{return alert('O arquivo selecionado não é um backup válido (.json).')}
 if(!Array.isArray(j.contatos)||!Array.isArray(j.negocios))return alert('Este arquivo não parece ser um backup do CRM Vorax.');
 if(!confirm(`Importar ${j.contatos.length} contatos, ${j.negocios.length} negócios e ${(j.produtos||[]).length} produtos? Isto substitui todos os dados atuais.`))return;
 this.exp('pre');for(const k of ['contatos','negocios','tarefas','interacoes','produtos','negocio_produtos'])D[k]=Array.isArray(j[k])?j[k]:[];D.empresa=j.empresa||{};commit('Backup importado com sucesso.')};i.click()}}
};
const cnome=id=>g('contatos',id)?.nome||'',
pnomes=n=>D.negocio_produtos.filter(x=>x.negocio_id==n.id).map(x=>(x.nome_produto||'Produto removido')+(x.quantidade!=1?` (x${fq(x.quantidade)})`:'')).join(', '),
csv=t=>{const r=[];let a=[''],q=0;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c=='"'){if(t[i+1]=='"'){a[a.length-1]+='"';i++}else q=0}else a[a.length-1]+=c}else if(c=='"')q=1;else if(c==','||c==';')a.push('');else if(c=='\n'){r.push(a);a=['']}else if(c!='\r')a[a.length-1]+=c}r.push(a);return r};

/* ---------- navegação ---------- */
const render=()=>{const v=V[S.tab];$('#nav').innerHTML=Object.entries(V).map(([k,x])=>`<button data-go="${k}" class="${k==S.tab?'on':''}">${x.title}</button>`).join('');$('#h').textContent=v.title;$('#bar').innerHTML=v.bar();$('#view').innerHTML=v.list();$('#co').textContent=D.empresa?.nome||'Gestão de clientes'};
const go=t=>{S={tab:t,q:'',cat:ALL,est:'Todos',stt:'Todas',rec:true};render()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-go],[data-a]');if(!b)return;if(b.dataset.go)return go(b.dataset.go);V[S.tab][b.dataset.a]?.(+b.dataset.id)});
document.addEventListener('input',e=>{const k=e.target.dataset.s;if(k){S[k]=e.target.type=='checkbox'?e.target.checked:e.target.value;$('#view').innerHTML=V[S.tab].list()}});
document.addEventListener('change',e=>{if(e.target.id!='lg'||!e.target.files[0])return;const r=new FileReader();r.onload=()=>{S.logo=r.result;$('#pv').src=r.result;$('#pv').hidden=false};r.readAsDataURL(e.target.files[0])});
(async()=>{const s=await load();if(s)D={...D,...s};navigator.storage?.persist?.();go('dashboard')})();
